// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClsFWpYhs-DOWJ36Y8xY320XS2ItK3kMo',
    appId: '1:499066921315:web:834c6c9ebbcf00bdd2b356',
    messagingSenderId: '499066921315',
    projectId: 'vs6451071010',
    authDomain: 'vs6451071010.firebaseapp.com',
    storageBucket: 'vs6451071010.firebasestorage.app',
    measurementId: 'G-HE2V96YH8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5m4vo8Rf71JY9IAlygWj1Hq0hBKrlddE',
    appId: '1:499066921315:android:1c1f2eade9e4c58cd2b356',
    messagingSenderId: '499066921315',
    projectId: 'vs6451071010',
    storageBucket: 'vs6451071010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsCLVliXc59GXDMqrMeJuyfeE1-MCahGY',
    appId: '1:499066921315:ios:c8e7ac32099937eed2b356',
    messagingSenderId: '499066921315',
    projectId: 'vs6451071010',
    storageBucket: 'vs6451071010.firebasestorage.app',
    iosBundleId: 'com.example.mapApp64510710356451071010',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsCLVliXc59GXDMqrMeJuyfeE1-MCahGY',
    appId: '1:499066921315:ios:c8e7ac32099937eed2b356',
    messagingSenderId: '499066921315',
    projectId: 'vs6451071010',
    storageBucket: 'vs6451071010.firebasestorage.app',
    iosBundleId: 'com.example.mapApp64510710356451071010',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClsFWpYhs-DOWJ36Y8xY320XS2ItK3kMo',
    appId: '1:499066921315:web:05f8e769a682e6fed2b356',
    messagingSenderId: '499066921315',
    projectId: 'vs6451071010',
    authDomain: 'vs6451071010.firebaseapp.com',
    storageBucket: 'vs6451071010.firebasestorage.app',
    measurementId: 'G-TK5YBJS28F',
  );
}
